-
    name: 'Execute a command to display hosts file on localhost'
    hosts: web_node1
    tasks:
        -
            name: 'Execute a command to display hosts file'
            command: cat /etc/hosts
-   
    name: 'Execute a command to display hosts file contents on web_node2'
    hosts: web_node2
    tasks:
        -
            name: 'Execute a command to display hosts file'
            command: 'cat /etc/hosts'
