-
    name: 'Execute a script on all web server nodes'
    hosts: web_nodes
    vars: 
      server_ip: 10.1.250.10
    tasks:
        -
            name: 'Update entry into /etc/resolv.conf'
            lineinfile:
                path: /etc/resolv.conf
                line: 'nameserver {{ server_ip }}'
        - 
            name: 'Create a new User'
            user:
              name: web_user
              uid: 1040
              group: developers
        -
            name: 'Execute a script on all web server nodes'
            script: /tmp/install_script.sh
        -
            name: 'Start httpd services'
            service:
                name: httpd
                state: started